--- ##### playbook to install and run docker on remote host
- hosts: all
  become: yes
  tasks:

    - name: Install containerd.io repo on host
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.5-3.1.el7.x86_64.rpm
        state: present

    - name: Install docker-ce-cli repo on host
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-cli-18.09.6-3.el7.x86_64.rpm
        state: present

    - name: Install container-selinux repo on host
      yum:
        name: http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm
        state: present

    - name: Install docker-ce repo on host
      yum:
        name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.6-3.el7.x86_64.rpm
        state: present

    - name: Start docker on host
      command: systemctl start docker

